
version: "3.3"
services:

  reverse-proxy:
    image: nginx:1.17
    container_name: reverse_proxy
    depends_on:
      - streamlit-app
      - dateideas-api
    ports:
      - "80:80"
    volumes:
        - ./reverse_proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-network

  streamlit-app:
    image: continuumio/miniconda3
    container_name: streamlit-app
    command: bash -c "pip install streamlit 
                      && streamlit run app/streamlit_app.py --server.port 8080" # --server.address=localhost
    ports: 
      - "8080:8080"
    volumes: 
     - type: bind
       source: ./streamlit_app
       target: /app
    networks:
      - nginx-network
    restart: on-failure
  
  dateideas-api:
    image: node:slim
    container_name: dateideas-api
    command: bash -c "node app/app.js"
    ports:
      - "3000:3000" ## remove in the future
    volumes: 
     - type: bind
       source: ./http_api
       target: /app
    networks:
      - nginx-network
    restart: on-failure
    env_file:
      - ./http_api/http_app.env
networks:
  nginx-network:
    driver: bridge
