
version: "3.9"
services:

  reverse-proxy:
    image: nginx:1.17
    container_name: reverse_proxy
    depends_on:
      - streamlit-app
      - dateideas-api
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./reverse_proxy/nginx.conf
        target: /etc/nginx/nginx.conf
    
  streamlit-app:
    image: continuumio/miniconda3
    container_name: streamlit_app
    command: bash -c "pip install streamlit 
                      && streamlit run app/streamlit_app.py --server.port 8080"
    ports: 
      - "8080:80"
    volumes: 
     - type: bind
       source: ./streamlit_app
       target: /app

  
  dateideas-api:
    image: node:slim
    container_name: dateideas_api
    command: bash -c "node app/app.js"
    ports:
      - "3000:3000"
    volumes: 
     - type: bind
       source: ./http_api
       target: /app

networks:
  ingress-network:
    driver: bridge
  internal-network:
    driver: bridge
